---
kind: pipeline
name: test

steps:

  - name: test
    image: golang:1.12
    environment:
      VERSION: ${DRONE_TAG:-${DRONE_COMMIT}}
    commands:
      - make build
      - make test

  - name: check
    image: python:3
    commands:
      - pip install pre-commit==1.20.0
      - make check

  - name: notify
    image: drillster/drone-email
    settings:
      host:
        from_secret: SMTP_HOST
      username:
        from_secret: SMTP_USER
      password:
        from_secret: SMTP_PASS
      from: drone@iamthefij.com
    when:
      status: [changed, failure]

---
kind: pipeline
name: publish

depends_on:
  - test

trigger:
  event:
    - push
    - tag
  refs:
    - refs/heads/master
    - refs/tags/v*

steps:
  - name: build all binaries
    image: golang:1.12
    environment:
      VERSION: ${DRONE_TAG:-${DRONE_COMMIT}}
    commands:
      - make all-linux

  - name: push image - arm
    image: plugins/docker
    settings:
      repo: iamthefij/minitor-go
      auto_tag: true
      auto_tag_suffix: linux-arm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - ARCH=arm
        - REPO=arm32v7

  - name: push image - arm64
    image: plugins/docker
    settings:
      repo: iamthefij/minitor-go
      auto_tag: true
      auto_tag_suffix: linux-arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - ARCH=arm64
        - REPO=arm64v8

  - name: push image - amd64
    image: plugins/docker
    settings:
      repo: iamthefij/minitor-go
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: publish manifest
    image: plugins/manifest
    settings:
      spec: manifest.tmpl
      auto_tag: true
      ignore_missing: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: notify
    image: drillster/drone-email
    settings:
      host:
        from_secret: SMTP_HOST
      username:
        from_secret: SMTP_USER
      password:
        from_secret: SMTP_PASS
      from: drone@iamthefij.com
    when:
      status: [changed, failure]
