version: "2"
linters:
  enable:
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - gosec
    - govet
    - ineffassign
    - misspell
    - mnd
    - modernize
    - staticcheck
    - tagalign
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unused
    - wrapcheck
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - common-false-positives
    rules:
      - linters:
          - gosec
        path: _test\.go
formatters:
  enable:
    - gofumpt
    - goimports
